services:
  db:
    container_name: beauty_salon_db
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: beauty_salon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
  data-generator:
    build: .
    depends_on:
      - db
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: user
      PG_PASSWORD: password
      PG_DB: beauty_salon
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data:
